services:
  devcontainer:
    container_name: ${DEVCONTAINER_NAME}
    {%- if cookiecutter.accelerator in ["cuda", "rocm"] %}

    # Give PyTorch workers enough memory!
    shm_size: '20gb'
    {%- endif %}

    # load environment variables from a dotenv file
    env_file:
      - .env
      # uncomment to load secrets from a dotenv file - do not commit
      # optionally add property "optional: true" to ignore if file is missing
      # - .env-secrets

    # necessary to keep devcontainer alive
    entrypoint: "sleep infinity"

    build:
      context: ..
      dockerfile: Dockerfile
      # build to stage 'dev'
      target: dev
      # set args for build process
      args:
        {%- if cookiecutter.accelerator == "cuda" %}
        # The CUDA version specified here must match the one in Dockerfile
        FROM_IMAGE: "nvidia/cuda:12.4.1-runtime-ubuntu22.04"
        {%- elif cookiecutter.accelerator == "rocm" %}
        # The ROCm version specified here must match the one in Dockerfile
        FROM_IMAGE: "rocm/dev-ubuntu-22.04:6.2"
        {%- endif %}
        VENV_PATH: "/opt/venv"
        PYTHON_VERSION: "{{ cookiecutter.python_version }}"
    {%- if cookiecutter.accelerator == "cuda" %}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    {%- elif cookiecutter.accelerator == "rocm" %}

    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    {%- endif %}

    volumes:
      # Mounts the project folder to '/workspace'.
      {%- if cookiecutter.is_subproject | string == "True" %}
      - ../../../:/workspace:cached
      {%- else %}
      - ../:/workspace:cached
      {%- endif %}
